# Generated by Django 3.2.7 on 2021-09-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20210917_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplegdprmodel',
            options={'permissions': [('can_view_anonymized_fields', 'Can view anonymized fields')], 'verbose_name': 'ExampleGDPRModel', 'verbose_name_plural': 'ExampleGDPRModels'},
        ),
    ]
