# Generated by Django 3.2.7 on 2021-09-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_examplegdprmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleGDPRParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Example GDPR Parent Model',
                'verbose_name_plural': 'Example GDPR Parent Models',
            },
        ),
        migrations.AddField(
            model_name='examplegdprmodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_gdprs', to='example.examplegdprparentmodel'),
        ),
    ]
