# Generated by Django 3.2.7 on 2021-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20210920_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'M2MExampleModel',
                'verbose_name_plural': 'M2MExampleModels',
            },
        ),
        migrations.AddField(
            model_name='examplegdprmodel',
            name='m2m_testing_model',
            field=models.ManyToManyField(db_table='example_examplegdprmodel_m2mtestingmodel', related_name='examplegdprmodels', to='example.M2MExampleModel', verbose_name='m2m_testing_model'),
        ),
    ]
